### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by albertlast** [dragomano/Optimus#14]
When you care about postgres some changes are needed:
https://github.com/dragomano/Optimus/blob/e5f931dedeef0937078fdbaac3813515499c6ea6/Sources/Class-Optimus.php#L222
replace ifnull with coalesce, got the advantage that you can give unlimited amount of col.

the last issue is the use of double quote here: 
https://github.com/dragomano/Optimus/blob/e5f931dedeef0937078fdbaac3813515499c6ea6/Sources/Class-OptimusSitemap.php#L148

since you want only the year the best approache would be to use the unix timestamp
and convert this in your while loop below:
https://github.com/dragomano/Optimus/blob/e5f931dedeef0937078fdbaac3813515499c6ea6/Sources/Class-OptimusSitemap.php#L161-L162

```
$row['poster_time'] = date('Y', $row['poster_time']);
```

Advantage you also take the timezone information into the account,
which could otherwise provide issue when you a unix timestamp is around 31.12. and 1.1.

**Comment by dragomano** [comment]
Thanks. Did you mean [these changes](https://github.com/dragomano/Optimus/commit/bf0c1e81e1e06179f867c3de2e552b690491a341)?

**Comment by albertlast** [comment]
yes this should work (i didn't installed you mod, i only look throw)
