### ISSUE TITLE
Link to sitemap on mobile devices - SMF 2.1 

### ISSUE THREAD

**Issue by mastum** [dragomano/Optimus#18]
With SMF 2.1 RC1 default theme I have this error when mobile devices browser the forum.

The file "optimus.css" could not be located on the current or the default theme and therefore it wasn't included in the minified file.

Thanks

**Comment by dragomano** [comment]
Can you provide any screenshots of your errors/problems? Use mobile device for it.

**Comment by mastum** [comment]
Sorry, I can not reproduce the error anymore 🤔
Thanks
