### ISSUE TITLE
Problem with tapatalk plugin

### ISSUE THREAD

**Issue by gazza07** [dragomano/Optimus#22]
Tapatalk doesnt work with this mod installed it just shows an error on the mobile device anychance of fixing this quite a few of my members use tapatalk, There is no error shown in the forum log
![Screenshot_20190619-044101](https://user-images.githubusercontent.com/4895797/59735691-95cf3580-924e-11e9-9291-cc0eb64fcc58.jpg)

**Comment by dragomano** [comment]
https://www.simplemachines.org/community/index.php?topic=567999.msg4020782#msg4020782

**Comment by gazza07** [comment]
How is that link even remotely similar to my problem ? tapatalk is installed and working 100% on SMF v2.1rc2, If I install optimus then it stops tapatalk from working with the error shown in the previous post,
I'm not having any problem uninstalling anything.

**Comment by dragomano** [comment]
Sorry, I cannot provide compatibility with all existing mods, especially unofficial.

**Comment by dragomano** [comment]
Try to add this line
`require_once($sourcedir . '/Optimus/Subs.php');`
before the line 84 in Integration.php

**Comment by gazza07** [comment]
Nice one thank you that appears to have fixed the problem tapatalk now works fine, Ive added a snippet of the code as I added it below

`// Favicon
		if (!empty($modSettings['optimus_favicon_text'])) {
			$favicon = explode("\n", trim($modSettings['optimus_favicon_text']));
			foreach ($favicon as $fav_line)
				$context['html_headers'] .= "\n\t" . $fav_line;
		}

		// TapaTalk Fix Bugo
		global $sourcedir; require_once($sourcedir . '/Optimus/Subs.php');

		// Counters
		Subs::addCounters();

		// Addons
		Subs::runAddons();`
