### ISSUE TITLE
Undefined index: meta_keywords_note

### ISSUE THREAD

**Issue by mastum** [dragomano/Optimus#25]
**To Reproduce**
Happens when trying to configure the mod

8: Undefined index: meta_keywords_note
 https://www.site.info/index.php?action=admin;area=optimus;a3c057a4f42=99ebfdb0bd4b92c00d6ea39de10b50cd
 /home/public_html/Sources/Optimus/Settings.php (Riga 177)

**Environment**
- Version/Git revision: e6a993786a3b3bc2e8bff904abf8d693a4f03e3b

**Comment by dragomano** [comment]
Does [v2.7.1](https://github.com/dragomano/Optimus/commit/d5a52839639252e271c4e56df19560abc60d80a8) fix it?

**Comment by mastum** [comment]
Yes!
Many thanks 😊
