### ISSUE TITLE
!Fix meta tag og:image always displays

### ISSUE THREAD

**Issue by tuivodich** [dragomano/Optimus#26]
Hello, the meta tag "og:image" always displays on the website whether we check "Use the image from the first topic message in the meta tag og:image" or not.

I think we should fix a litte bit in **Sources/Optimus/Subs.php**
Find (line 150):
` if (empty($settings['og_image'])) {`
Replace with:
`if (empty($modSettings['optimus_og_image'])) {`

**Comment by dragomano** [comment]
**og:image** is a required tag, see https://www.ogp.me/ for additional info.

**Comment by tuivodich** [comment]
I see mate, but when we want to use first topic image on the facebook, then the og:image shouldn’t be display!
That’s just a little fix. Please see in action on my fanpage: [https://facebook.com/layphatvn](https://facebook.com/layphatvn) . It’s using both first topic image and og:image website setting!

**Comment by dragomano** [comment]
Your fix works with Facebook, I see. But what about other services? For example, Yandex Webmaster shows an error due og:image is empty/not exist.

**Comment by dragomano** [comment]
I removed this block fully, see the [commit](https://github.com/dragomano/Optimus/commit/7ae9dfebcb76ee3f645e6e88d987818307803bbb)

**Comment by tuivodich** [comment]
> I removed this block fully, see the [commit](https://github.com/dragomano/Optimus/commit/7ae9dfebcb76ee3f645e6e88d987818307803bbb)

Nice, but actually we still have the $modSettings['optimus_og_image'] value at the Admin CP: yourforum/index.php?action=admin;area=optimus;sa=extra, that we can chose option "Use the image from the first topic message in the meta tag og:image" or use OG Image on current theme! [defined with function extraTabSettings($return_config = false)  in Sources/Optimus/Settings.php]

On my opinion, we should hold that block, with a little bit change that i would recommend!
