### ISSUE TITLE
Cannot show sitemap xml, it shows error ouput header and footer!

### ISSUE THREAD

**Issue by tuivodich** [dragomano/Optimus#27]
**Describe the bug**
Cannot show sitemap xml, it shows error ouput header and footer!

**To Reproduce**
1. Install SMF 2.1.x and this Optimus mod
2. Go to Admin CP --> Optimus setting --> Activate the Sitemap area
3. Browser link: youforum/index.php?action=sitemap;xml

**Fix solution**
Open file **Sources\Optimus\Sitemap.php**.
Find (line 73 - 75):
```
	public static function getXml()
	{
		global $modSettings, $context, $scripturl;
```
Replace with:
```
	public static function getXml()
	{
		global $modSettings, $context, $scripturl;
		loadTemplate('Optimus');
```

**Comment by dragomano** [comment]
I can't reproduce it. Are you using the latest build of OP?

**Comment by tuivodich** [comment]
Oh sorry, that's my fault. This error happens when i use 2 mods: Sitemap by Matt Zuba and this Optimus mod. I modified some changes for them to work together! And both works perfectly!
