### ISSUE TITLE
PHP 7.4 error

### ISSUE THREAD

**Issue by radu81** [dragomano/Optimus#32]
I am using this add-on on Elkarte 1.1.6 and I am doing some tests with PHP 7.4, after every page refresh I get this error on Elkarte log:
    Type of error: General
    Unknown Error: implode(): Passing glue string after array is deprecated. Swap the parameters
    /index.php?action=mentions;sa=fetch;api=json;lastsent=0
    File: /public/sources/subs/Optimus.class.php
    Line: 290

289: | if (!empty($list_item))
290: | $context['insert_after_template'] .= implode($list_item, ',');
291: |  
292: | $context['insert_after_template'] .= ']

Is there any way to fix this? Thank you in advance

**Comment by dragomano** [comment]
Thanks, I will release a fix soon.

**Comment by radu81** [comment]
Thank you dragomano. 
In the meantime Spuds found a solution, change line 290 with
`$context['insert_after_template'] .= implode(',', $list_item);`
