### ISSUE TITLE
Задвоение счетчиков

### ISSUE THREAD

**Issue by iCr** [dragomano/Optimus#33]
Приветствую! 
Версия мода: 2.7.1, версия PHP: 7.3.8, версия MySQL: 5.7.26

На днях обновил древний Optimus до самой свежей версии, после чего **счетчики с загрузкой в секции head (Google Analytics)** и **Обычные счётчики** начали задваиваться.
Сначала я думал что это какой-то мой косяк, но потом понял что это какая-то мистика.
![Снимок экрана 2021-03-02 в 0 42 45](https://user-images.githubusercontent.com/2919380/109563003-3c756b80-7af0-11eb-89d5-d9545c90b9e4.png)

![Снимок экрана 2021-03-02 в 0 41 38](https://user-images.githubusercontent.com/2919380/109562933-1cde4300-7af0-11eb-9966-cf2bff38aeb5.png)

Как это выглядит, сейчас можно посмотреть на продакшене https://forum.cadstudio.ru

**Comment by dragomano** [comment]
В старых версиях переменные для хранения счетчиков назывались иначе, но поскольку информацию они выводили в тех же местах, вот и дублирование. Посмотрите в базе данных в таблице smf_settings (префикс может быть другим!), поищите, в каких полях содержатся дублирующие значения, потом напишите сюда названия этих полей.

**Comment by iCr** [comment]
Задвоений в таблицах на первый взгляд не видно, задампил относящееся к оптимусу:

`INSERT INTO `smf_settings` (`variable`, `value`) VALUES
('integrate_admin_areas', 'optimus_admin_areas,Tapatalk_add_admin_areas,fancy_admin_areas,DevCenter_adminArea'),
('integrate_admin_include', '$sourcedir/Admin-Optimus.php'),
('integrate_buffer', 'optimus_buffer,spoiler_buffer,fancy_buffer'),
('integrate_create_topic', 'optimus_sitemap'),
('integrate_load_theme', 'optimus_home,spoiler_load_theme,fancy_load_theme'),
('integrate_menu_buttons', 'optimus_operations,fancy_menu_buttons,DevCenter_ErrorLogCount'),
('integrate_modify_modifications', 'fancy_modifications,DevCenter_prepareSettings'),
('integrate_mod_buttons', 'TopicRenamer_mod_buttons'),
('integrate_output_error', 'DevCenter_LogError'),
('integrate_pre_include', '$sourcedir/Subs-Optimus.php,$sourcedir/Subs-QuickSpoiler.php,$sourcedir/Subs-Tapatalk.php,$sourcedir/Subs-Fancy.php,$sourcedir/TopicRenamer.php,$sourcedir/Mod-Microdata4Smf.php,$sourcedir/Mod-Dquote.php,$sourcedir/Optimus/app.php,$sourcedir/Subs-DevCenter.php,$sourcedir/Mod-TopFirstPost.php,$sourcedir/Mod-CacheStats.php'),
('integrate_pre_load', 'loadMicrodata4SmfHooks,loadDquoteHooks,Tapatalk_add_save_forum_version,DevCenter_PreLoad,loadTopFirstPostHooks,loadCacheStatsHooks'),
('optimus_404_status', '1'),
('optimus_board_description', '1'),
('optimus_counters_css', '.copyright a>img {opacity: 0.3} .copyright a:hover>img {opacity: 1.0}'),
('optimus_count_code', '....'),
('optimus_description', 'Форум '),
('optimus_forum_index', 'Главная'),
('optimus_head_code', ''),
('optimus_ignored_actions', 'admin,helpadmin,printpage'),
('optimus_no_first_number', '1'),
('optimus_og_image', '//xxx/images/thumbnail.gif'),
('optimus_remove_previous_xml_files', '0'),
('optimus_root_path', '/xxx/www'),
('optimus_sitemap_boards', '1'),
('optimus_sitemap_enable', '1'),
('optimus_sitemap_items_display', '10000'),
('optimus_sitemap_link', '1'),
('optimus_sitemap_topics_num_replies', '2'),
('optimus_stat_code', '...'),
('optimus_topic_description', '1');`

**Comment by dragomano** [comment]
Я вообще здесь не вижу строчки `adsbygoogle.js` из скрипта, который дублируется. Может это хвост от другого мода, типа Ad Management mod? Либо подключение скрипта прописано где-нибудь в файлах темы.

**Comment by iCr** [comment]
Я пока ее убрал, но задваиваются не только гугловские, а вообще любые. Тот же счетчик @Mail.ru также задвоен (в коде убрал содержимое счетчика).
Ad management mod отключен.

**Comment by dragomano** [comment]
Если полностью убрать код счетчика в настройках Оптимуса, он не выводится вообще или всё ещё выводится, но только 1 раз? Если все равно выводится, значит где-то в index.template.php темы (а она у вас нестандартная) скрипты подключатся более 1 раза.

**Comment by iCr** [comment]
@dragomano проблема оказалась намного глубже. После обновления AD Management mod у меня задвоились и баннеры которые выводятся через этот адд-он.
Создается впечатление, что задваиваются абсолютно все новые хуки.
Какая-то совсем дичь (((

**Comment by dragomano** [comment]
Значит, где-то остались хвосты от Ad Management, если несколько раз устанавливали, удаляли.
На чистой установке проверьте работу Оптимуса, если счетчики не будут удваиваться, можно закрывать тему.

**Comment by iCr** [comment]
Уже всё перепроверил трижды, поиском по файлам, базе данных. Нигде никаких хвостов не осталось.
При этом карта ссылка оптимуса на генерируемую им карту форума инклюдится один раз:
![Снимок экрана 2021-03-02 в 22 56 10](https://user-images.githubusercontent.com/2919380/109706866-86228c80-7baa-11eb-8070-2a4d59d46921.png)

**Comment by dragomano** [comment]
Если старую версию мода удалили, откуда тогда в базе данных подключение хука Admin-Optimus.php?
