### ISSUE TITLE
Плохой баг

### ISSUE THREAD

**Issue by woodholly** [dragomano/Optimus#34]
В meta description слова через "br" и другие блочные разделители объёдиняются без пробела. Пофикси в getTeaser:
```php
$text = preg_replace('/<\/?(?:p|br|hr|li|div|blockquote|code|td)\b[^>]*>/i', " ", $text);
```

**Comment by woodholly** [comment]
закрывать тикет без коммента ? очень приятно, впредь буду всё исправлять только у себя
баг то остался, как в 2.0 так и в 2.1

**Comment by dragomano** [comment]
Описание не по шаблону, и я должен угадывать, в какой именно версии баг искать?
