### ISSUE TITLE
XSS в коде

### ISSUE THREAD

**Issue by woodholly** [dragomano/Optimus#35]
куда писать об уязвимости ?

**Comment by dragomano** [comment]
https://github.com/dragomano/Optimus/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by woodholly** [comment]
Впрочем не всё так серьёзно как я думал, всего-лишь создатель борды может вставить любой код.
$context["meta_tags"] не квотится, пример:
```html
<meta prefix="article: http://ogp.me/ns/article#" property="article:section" content="Section name "section name in quotes"">
```
.. or .. should it be quoted by user ?

**Comment by woodholly** [comment]
Я у себя тоже не могу повторить, видимо пофиксил. Замечу снова - напишу.
