### ISSUE TITLE
SMF 2.1 support

### ISSUE THREAD

**Issue by smartm0use** [dragomano/Optimus#36]
Hello, readme says that "The master branch contains the Optimus 2.x version for SMF 2.1 RC3+".

I can't see any master branch here. I get "smf20.zip", but as the filename suggests, it doesn't support SMF version 2.1.
Where can I get it?

**Comment by dragomano** [comment]
Thanks, fixed.

**Comment by smartm0use** [comment]
So, no support for 2.1?

**Comment by dragomano** [comment]
Wait for the 2.1 Final. Unfortunately, at the current moment, I have no time, no funds, nor desire to continue this development.
