### ISSUE TITLE
2.1 version topic name not used

### ISSUE THREAD

**Issue by bensene** [dragomano/Optimus#4]
Fresh vanilla install, installed this mod
Enabled mod, settings as default.

Welcome to SMF topic
?topic=1.0

the title/description 
	<title> - page 1 - General Discussion - My Community</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property="og:site_name" content="My Community">
	<meta property="og:title" content=" - page 1 - General Discussion - My Community">
	<meta property="og:url" content="http://localhost/smf/?topic=1.0">
	<meta property="og:description" content=" - page 1 - General Discussion - My Community">
	<meta name="description" content=" - page 1 - General Discussion - My Community">

Appears to relate to Subs-Optimus.php line 282
 "{topic_name}" => $topicinfo['subject'],

 $topicinfo['subject'] is blank.

**Comment by Yariksat** [comment]
Subs-Optimus.php line 282
`"{topic_name}" => $topicinfo['subject'],`
replace the
`"{topic_name}" => $context['topicinfo']['subject'],`
