### ISSUE TITLE
Админка оптимуса

### ISSUE THREAD

**Issue by Yariksat** [dragomano/Optimus#8]
В самой последней версии мода после установки в админке отсутсвуют настройки мода.Откатился на старую версию мода.

**Comment by dragomano** [comment]
А когда мод скачивали? Версия не менялась, но фикс этот я уже вносил, должно устанавливаться без проблем теперь.

**Comment by Yariksat** [comment]
Упс,тогда извиняюсь.Сейчас работает все нормально
